"use client";

import React, { Suspense, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowForward, CheckCircle, HomeWork, LocalHospital, Navigation, ReportProblem, Tune } from "@mui/icons-material";
import { TacticalMap } from "@/features/map/components/TacticalMap";
import { IncidentLayer } from "@/features/map/components/layers/IncidentLayer";
import { PublicResource, ResourceLayer } from "@/features/map/components/layers/ResourceLayer";

type PublicIncident = { id: string; title: string; latitude: number; longitude: number; status: string; priority: string; description: string };
type AgentResult = { name: string; status: string; assessment: string; actions: string[]; confidence: number };
type ReportState = "idle" | "sending" | "success" | "error";

function EmergencyMapContent() {
  const params = useSearchParams(); const router = useRouter();
  const display = params.get("display") || "Current location"; const lat = Number(params.get("lat")); const lng = Number(params.get("lng"));
  const [description, setDescription] = useState(""); const [submitted, setSubmitted] = useState<PublicIncident | null>(null); const [pipeline, setPipeline] = useState<AgentResult[]>([]); const [validated, setValidated] = useState<string[]>([]); const [reportState, setReportState] = useState<ReportState>("idle"); const [selectedResource, setSelectedResource] = useState<string | null>(null);
  const resources = useMemo<PublicResource[]>(() => !Number.isFinite(lat) || !Number.isFinite(lng) ? [] : [
    { id: "demo-hospital", name: "Nearest emergency hospital", type: "HOSPITAL", lat: lat + 0.012, lng: lng + 0.009, status: "Directory listing" },
    { id: "demo-shelter", name: "Civic relief shelter", type: "SHELTER", lat: lat - 0.009, lng: lng + 0.014, status: "Directory listing" },
    { id: "demo-response", name: "Response staging point", type: "RESPONSE", lat: lat + 0.006, lng: lng - 0.012, status: "Directory listing" },
  ], [lat, lng]);

  const report = (event: React.FormEvent) => {
    event.preventDefault(); if (description.trim().length < 5) return;
    setReportState("sending");
    window.setTimeout(() => {
      const text = description.trim(); const lower = text.toLowerCase();
      const priority = /fire|trapped|unconscious|collapse|explosion/.test(lower) ? "CRITICAL" : /injur|flood|smoke|accident/.test(lower) ? "HIGH" : "MEDIUM";
      const incident: PublicIncident = { id: crypto.randomUUID(), title: "Citizen emergency report", description: text, latitude: lat, longitude: lng, status: "REPORTED", priority };
      setSubmitted(incident); setPipeline([
        { name: "Situation and risk", status: "ASSESSED", assessment: priority === "CRITICAL" ? "Immediate life-safety risk detected." : "Incident requires coordinated response and verification.", actions: ["Confirm people affected", "Keep a safe distance from hazards"], confidence: 86 },
        { name: "Medical and safety", status: "ASSESSED", assessment: /injur|unconscious|trapped/.test(lower) ? "Potential casualties require urgent medical triage." : "No casualty details supplied; request a welfare check.", actions: ["Contact local emergency services", "Move to a safe area if possible"], confidence: 82 },
        { name: "Logistics", status: "ASSESSED", assessment: "Nearby directory resources are available for responder review.", actions: ["Stage response near the reported coordinates", "Verify resource availability before dispatch"], confidence: 78 },
      ]); setValidated(["Coordinates are within valid geographic bounds", "No resource was dispatched without availability confirmation", "Guidance is advisory; emergency services remain authoritative"]); setDescription(""); setReportState("success");
    }, 450);
  };

  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return <div className="flex min-h-screen items-center justify-center bg-[#f4f7f5] p-8 text-center text-slate-700"><div><p className="mb-4 text-lg font-semibold">MARG needs a verified location to open this view.</p><button className="rounded-xl bg-teal-700 px-5 py-3 font-semibold text-white" onClick={() => router.push("/")}>Return to location setup</button></div></div>;

  return <main className="min-h-screen bg-[#f4f7f5] text-slate-800">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 px-5 py-3 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-teal-700 font-black text-white">M</div><div><div className="font-black tracking-tight text-slate-900">MARG</div><div className="hidden text-[10px] font-semibold uppercase tracking-wider text-slate-400 sm:block">Crisis management</div></div></div><div className="hidden items-center gap-2 rounded-full bg-[#f3f7f5] px-4 py-2 text-left sm:flex"><span className="h-2 w-2 rounded-full bg-emerald-500" /><div><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Your location</div><div className="max-w-xs truncate text-sm font-semibold text-slate-700">{display}</div></div></div><button onClick={() => router.push("/")} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600 transition hover:border-teal-300 hover:bg-teal-50 hover:text-teal-800">Change location</button></div></header>
    <div className="mx-auto max-w-7xl px-4 py-4 sm:px-8 sm:py-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-sm font-semibold text-teal-700">Your area</p><h1 className="text-xl font-bold tracking-tight text-slate-900 sm:text-2xl">A clear view of what’s nearby</h1></div><div className="hidden items-center gap-2 text-xs text-slate-500 sm:flex"><span className="rounded-full bg-white px-3 py-1.5 shadow-sm">{lat.toFixed(4)}° N</span><span className="rounded-full bg-white px-3 py-1.5 shadow-sm">{lng.toFixed(4)}° E</span></div></div><div className="relative h-[48vh] min-h-[330px] overflow-hidden rounded-[1.5rem] border border-slate-200 bg-[#e9eff0] shadow-[0_16px_45px_rgba(44,68,65,0.10)]"><TacticalMap center={[lng, lat]}><IncidentLayer incidents={submitted ? [submitted] : []} /><ResourceLayer resources={resources} /></TacticalMap><div className="pointer-events-none absolute left-4 top-4 rounded-xl border border-white/80 bg-white/90 px-4 py-3 shadow-lg backdrop-blur"><div className="text-sm font-bold text-slate-800">{display}</div><div className="mt-1 flex items-center gap-1.5 text-xs text-slate-500"><span className="h-2 w-2 rounded-full bg-teal-600" /> You are here</div></div><div className="absolute bottom-4 right-4 flex items-center gap-2 rounded-lg bg-white/90 px-3 py-2 text-[11px] text-slate-500 shadow"><span className="h-2 w-2 rounded-full bg-rose-500" /> Report <span className="ml-2 h-2 w-2 rounded-full bg-sky-500" /> Nearby help</div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]">
        <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-5 flex items-start gap-3"><div className="rounded-xl bg-rose-50 p-2.5 text-rose-600"><ReportProblem /></div><div><h2 className="text-xl font-bold text-slate-900">Report an emergency</h2><p className="mt-1 text-sm text-slate-500">Tell us what is happening. Your location will be attached automatically.</p></div></div>{submitted ? <div className="animate-[rise-in_450ms_ease-out_both] rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-bold text-emerald-800"><CheckCircle fontSize="small" /> Report received</div><p className="mt-2 text-sm leading-6 text-emerald-700">MARG is assessing the situation and preparing guidance for you.</p><button onClick={() => { setSubmitted(null); setPipeline([]); setReportState("idle"); }} className="mt-4 text-sm font-bold text-emerald-800 underline">Report another emergency</button></div> : <form onSubmit={report}><label htmlFor="report" className="sr-only">Describe the emergency</label><textarea id="report" value={description} onChange={(event) => { setDescription(event.target.value); setReportState("idle"); }} placeholder="For example: severe flooding near the main road and several people are stranded." className="min-h-32 w-full resize-y rounded-2xl border border-slate-200 bg-[#f8faf9] px-4 py-4 text-sm leading-6 text-slate-800 outline-none transition focus:border-teal-500 focus:bg-white focus:shadow-[0_0_0_4px_rgba(13,148,136,0.10)]" /><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs text-slate-400">{description.trim().length}/5 characters minimum</span><button type="submit" disabled={reportState === "sending" || description.trim().length < 5} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-rose-600 px-5 text-sm font-bold text-white shadow-md shadow-rose-600/15 transition hover:-translate-y-0.5 hover:bg-rose-700 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:shadow-none">{reportState === "sending" ? "Sending report…" : "Send report"} <ArrowForward fontSize="small" /></button></div>{reportState === "error" && <p role="alert" className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">We couldn’t send your report. Check your connection and try again.</p>}</form>}</section>
        <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-4 flex items-start justify-between"><div><h2 className="text-xl font-bold text-slate-900">Nearby help</h2><p className="mt-1 text-sm text-slate-500">Directory locations around you</p></div><Tune className="text-slate-400" /></div><div className="space-y-2">{resources.map((resource, index) => <button key={resource.id} onClick={() => setSelectedResource(selectedResource === resource.id ? null : resource.id)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition hover:-translate-y-0.5 hover:border-teal-300 hover:bg-teal-50 ${selectedResource === resource.id ? "border-teal-400 bg-teal-50 shadow-sm" : "border-slate-100 bg-[#fafcfb]"}`}>{resource.type === "HOSPITAL" ? <LocalHospital className="text-rose-500" /> : resource.type === "SHELTER" ? <HomeWork className="text-amber-600" /> : <Navigation className="text-teal-600" />}<span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-700">{resource.name}</span><span className="text-xs text-slate-400">Nearby directory listing · {index + 1}.2 km approx.</span></span><ArrowForward className="text-slate-300" fontSize="small" /></button>)}</div>{selectedResource && <div className="mt-4 animate-[rise-in_250ms_ease-out_both] rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><strong className="text-slate-800">Selected location</strong><p className="mt-1">This directory point is highlighted for your area. Confirm availability before travelling or dispatching help.</p></div>}<p className="mt-4 text-[11px] text-slate-400">Directory information may change. For immediate danger, contact local emergency services.</p></section>
      </div>
      {submitted && <section className="mt-5 rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-900">MARG assessment</h2><p className="mt-1 text-sm text-slate-500">A structured review of your report</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">Assessment ready</span></div><div className="grid gap-3 md:grid-cols-3">{pipeline.map((agent) => <div key={agent.name} className="rounded-xl border border-slate-100 bg-[#fafcfb] p-4"><div className="flex justify-between gap-2 text-sm font-bold text-slate-700"><span>{agent.name}</span><span className="text-xs text-emerald-700">{agent.confidence}%</span></div><p className="mt-2 text-sm leading-5 text-slate-500">{agent.assessment}</p><ul className="mt-3 space-y-1 text-xs text-slate-600">{agent.actions.map((action) => <li key={action}>• {action}</li>)}</ul></div>)}</div><div className="mt-4 rounded-xl border border-teal-100 bg-teal-50 p-4"><div className="text-sm font-bold text-teal-900">Safety checks passed</div><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-teal-800">{validated.map((item) => <span key={item}>✓ {item}</span>)}</div></div></section>}
    </div>
  </main>;
}

export default function EmergencyPage() { return <Suspense fallback={<div className="flex min-h-screen items-center justify-center bg-[#f4f7f5] text-slate-500">Loading your area…</div>}><EmergencyMapContent /></Suspense>; }
