[alembic]
script_location = src/marg_api/infrastructure/database/migrations
prepend_sys_path = src
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:54322/postgres

[logging]
default_level = INFO
